srun: error: WARNING: switches lack access to 1 nodes: cn272
Importing core modules
 Using computational backend numpy on cpu
 Runtime settings are now locked

This is Veros v0+untagged.1783.ge272e4a.dirty, but the given setup was generated with v0+untagged.1774.g4039f76.dirty. Consider switching to this version of Veros or updating your setup file.

Running model setup
Initializing streamfunction method
Environment variable OMP_NUM_THREADS is not set, which can lead to severely degraded performance when MPI is used.
 Solving for boundary contribution by island 0
 Solving for boundary contribution by island 1
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
Traceback (most recent call last):
  File "/scratch/so2495/conda-envs/veros/bin/veros", line 8, in <module>
    sys.exit(cli())
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/so2495/conda-envs/veros/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 152, in cli
    return run(setup_file, *args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/cli/veros_run.py", line 86, in run
    sim.setup()
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/veros.py", line 230, in setup
    diagnostics.initialize(self.state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/api.py", line 19, in initialize
    diagnostic.initialize(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/averages.py", line 41, in initialize
    self.initialize_output(state)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/signals.py", line 34, in dnd_wrapper
    res = function(*args, **kwargs)
  File "/scratch/so2495/code/OceanHybridModels/veros/veros/diagnostics/base.py", line 75, in initialize_output
    raise IOError(
OSError: output file acc_runs/acc_simulation_quarter/acc_simulation_quarter.averages.nc for diagnostic "averages" exists (change output path or enable force_overwrite runtime setting)
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
There is one unused database option. It is:
Option left: name:-pc_gamg_sym_graph value: true source: code
